"""Shared implementation for Breadcrumb's deterministic scripts."""

SCRIPT_OUTPUT_SCHEMA_VERSION = 1

CURRENT_BACKLOG_DOCUMENT_SCHEMA_VERSION = 1
SUPPORTED_BACKLOG_DOCUMENT_SCHEMA_VERSIONS = frozenset({1})

CURRENT_REQUIREMENT_DOCUMENT_SCHEMA_VERSION = 2
SUPPORTED_REQUIREMENT_DOCUMENT_SCHEMA_VERSIONS = frozenset({1, 2})

CURRENT_DESIGN_DOCUMENT_SCHEMA_VERSION = 1
SUPPORTED_DESIGN_DOCUMENT_SCHEMA_VERSIONS = frozenset({1})
